platform :osx, "10.8"

target "MMLayerAccessibilityDemo" do
	pod "MMLayerAccessibility", :path => "../MMLayerAccessibility.podspec"
end

target "MMLayerAccessibilityDemoTests", :exclusive => true do
   pod 'Kiwi/XCTest', '2.2.3'
end