language: objective-c
rvm: 1.9.3
env:
  - XCWORKSPACE="Example/MMLayerAccessibilityDemo.xcworkspace"
before_install:
  - sudo easy_install cpp-coveralls
script: xcodebuild -workspace Example/MMLayerAccessibilityDemo.xcworkspace/ -scheme MMLayerAccessibilityDemo test
after_success:
  - ./coveralls.rb --extension m --exclude-folder Classes/osx/Specs --exclude-folder Example