language: objective-c
before_install:
  - cd Example
  - gem install cocoapods --no-ri --no-rdoc
  - pod install
  - cd ..
env:
  - XCWORKSPACE="Example/MMLayerAccessibilityDemo.xcworkspace"
script: xctool -workspace Example/MMLayerAccessibilityDemo.xcworkspace -scheme MMLayerAccessibilityDemo clean test
