language: objective-c
rvm: 1.9.3
env:
  - XCWORKSPACE="Example/MMLayerAccessibilityDemo.xcworkspace"
before_install:
  - sudo easy_install cpp-coveralls
script: xcodebuild -workspace Example/MMLayerAccessibilityDemo.xcworkspace/ -scheme MMLayerAccessibilityDemo CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO MM_IS_COVERAGE_BUILD=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES test
after_success:
  - ./coveralls.rb --extension m --exclude-folder Classes/osx/Specs --exclude-folder Example